node_config_network:
  activation_account_name: activator
  chain_name: TEZOS_RISKVNET_2025-09-11T12:00:00Z
  genesis:
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2025-09-11T12:00:00Z"
  dal_config:
    activated: true
    bootstrap_peers:
      - dal-bootstrap:11732

activation:
  protocol_hash: PtSeouLouXkxhg39oWzjxDWaCydNfR3RxCUrNe4Q9Ro8BTehcbh
  protocol_parameters:
    adaptive_rewards_params:
      issuance_ratio_final_min:
        numerator: "1"
        denominator: "400"
      issuance_ratio_final_max:
        numerator: "1"
        denominator: "10"
      issuance_ratio_initial_min:
        numerator: "9"
        denominator: "200"
      issuance_ratio_initial_max:
        numerator: "11"
        denominator: "200"
      initial_period: 10
      transition_period: 50
      max_bonus: "50000000000000"
      growth_rate:
        numerator: "1"
        denominator: "100"
      center_dz:
        numerator: "1"
        denominator: "2"
      radius_dz:
        numerator: "1"
        denominator: "50"
    aggregate_attestation: true
    all_bakers_attest_activation_level: null
    allow_tz4_delegate_enable: true
    blocks_per_commitment: 25
    blocks_per_cycle: 200
    blocks_preservation_cycles: 1
    cache_sampler_state_cycles: 5
    cache_script_size: 100000000
    cache_stake_distribution_cycles: 5
    consensus_committee_size: 7000
    consensus_rights_delay: 2
    consensus_threshold_size: 4667
    cost_per_byte: '250'
    cycles_per_voting_period: 1
    dal_parametric:
      feature_enable: true
      incentives_enable: true
      number_of_slots: 32
      number_of_shards: 512
      attestation_lag: 8
      attestation_threshold: 66
      slot_size: 126944
      redundancy_factor: 8
      page_size: 3967
      minimal_participation_ratio:
        numerator: "16"
        denominator: "25"
      rewards_ratio:
        numerator: "1"
        denominator: "10"
      traps_fraction:
        numerator: "1"
        denominator: "2000"
    delay_increment_per_round: "2"
    delegate_parameters_activation_delay: 3
    direct_ticket_spending_enable: false
    edge_of_staking_over_delegation: 2
    global_limit_of_staking_over_baking: 5
    hard_gas_limit_per_block: "3328000"
    hard_gas_limit_per_operation: "1040000"
    hard_storage_limit_per_operation: "60000"
    issuance_weights:
      attesting_reward_weight: 10240
      base_total_issued_per_minute: "85007812"
      baking_reward_fixed_portion_weight: 5120
      baking_reward_bonus_weight: 5120
      dal_rewards_weight: 0
      vdf_revelation_tip_weight: 1
      seed_nonce_revelation_tip_weight: 1
    limit_of_delegation_over_baking: 9
    liquidity_baking_subsidy: "5000000"
    liquidity_baking_toggle_ema_threshold: 100000
    max_operations_time_to_live: 120
    max_slashing_per_block: 10000
    max_slashing_threshold: 
      numerator: 1
      denominator: 3
    minimal_block_delay: "4"
    min_proposal_quorum: 500
    minimal_frozen_stake: "600000000"
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    minimal_stake: "6000000000"
    nonce_revelation_threshold: 50
    origination_size: 257
    percentage_of_frozen_deposits_slashed_per_double_baking: 700
    proof_of_work_threshold: "-1"
    quorum_max: 7000
    quorum_min: 2000
    smart_rollup_arith_pvm_enable: true
    smart_rollup_challenge_window_in_blocks: 62
    smart_rollup_commitment_period_in_blocks: 31
    smart_rollup_max_active_outbox_levels: 31500
    smart_rollup_max_lookahead_in_blocks: 346875
    smart_rollup_max_number_of_cemented_commitments: 5
    smart_rollup_max_number_of_parallel_games: 32
    smart_rollup_max_outbox_messages_per_level: 100
    smart_rollup_number_of_sections_in_dissection: 32
    smart_rollup_origination_size: 6314
    smart_rollup_private_enable: true
    smart_rollup_riscv_pvm_enable: true
    smart_rollup_stake_amount: "32000000"
    smart_rollup_timeout_period_in_blocks: 781
    smart_rollup_reveal_activation_level:
      raw_data:
        Blake2B: 0
      metadata: 0
      dal_page: 1
      dal_parameters: 1
      dal_attested_slots_validity_lag: 80
    tolerated_inactivity_period: 1
    vdf_difficulty: '10000000'
    zk_rollup_enable: true
    zk_rollup_origination_size: 4000
    zk_rollup_min_pending_to_process: 10
    zk_rollup_max_ticket_payload_size: 2048
  bootstrap_parameters:

nodes:
  tezos-baking-node:
    env:
      all:
        TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: "Y"
        # Configure structured logging for Google Cloud Logging
        TEZOS_LOG_LEVEL: "info"
        TEZOS_LOG_FORMAT: "json"
      baker:
        BAKER_EXTRA_ARGS: "--dal-node http://dal-dal1:10732"
    instances:
      - bake_using_accounts:
          - activator
          - bootstrap1
          - bootstrap2
          - bootstrap3
          - bootstrap4
          - bootstrap5
        dal_node_rpc_url: http://dal-dal1:10732
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
            max_active_rpc_connections: 1000
          metrics_addr: ["0.0.0.0:9932"]
        is_bootstrap_node: true
        identity:
          # hard-coded identity - saves 1-2 minutes on daily cron
          peer_id: idqnaeAw4oGfUEnKrLH2fZYRQo4Ev1
          public_key:
            c988f65dfbc50ef61d8db84b89ea8df93643328bbd0524321582e39d33e32115
          secret_key:
            38ffcb4629db7152141824835bebf42f12d90933d68773d78002f86637500b62
          proof_of_work_stamp: 3ee07208e41a0489299909c0bd3cac5c05b20a9acc4a3bc7
    runs:
      - octez_node
      - baker
      - accuser
      - vdf
    bootstrapped_readiness_probe: false
    storage_size: 100Gi



dalNodes:
  dal-bootstrap:
    bootstrapProfile: true
    node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
    storageSize: 100Gi
    env:
      all:
        # Configure structured logging for Google Cloud Logging
        TEZOS_LOG_LEVEL: "info"
        TEZOS_LOG_FORMAT: "json"
    ingress:
    # ingress details filled up by pulumi
    identity:
      peer_id: "idtJh8bYedP2hKdRk6oCLX3SS2KuTM"
      public_key:
        "5a6cd66cbd2f69817fb2eb81e5dd2a9c4f88df950fc90a96a08fe3976724a063"
      secret_key:
          "42f716781cf80b2b7ad129ac56dfcb1b333f3021e49c6729199de8303c7152c9"
      proof_of_work_stamp: "b7edd6ea938998f8f088b83b692baeddb49f5522f07572f9"
  dal-dal1:
    attest_using_accounts:
      - activator
    attesterProfiles: tz1a3bL5hVVibgbaJ7zM3uUJU1iHUgxxpVkU
    node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
    storageSize: 100Gi
    env:
      all:
        # Configure structured logging for Google Cloud Logging
        TEZOS_LOG_LEVEL: "info"
        TEZOS_LOG_FORMAT: "json"
    ingress:
    # ingress details filled up by pulumi
    identity:
      peer_id: "ids8gZ6Gu67e58DqPn2e9VyjasB1jo"
      public_key:
        "c4ea1f6dddfa43b87b6a37432c4c34e1c79baeed5ff165fee2a85ffafb819e5f"
      secret_key:
          "a67519da6166f97ca2dea6dc519f1a453d96e01348816d102fb9a7099ee08137"
      proof_of_work_stamp: "c85a3aab8a1fc903e8c7e9bcd1714a890e22f160a96d9779"

dal_deploy_slot_injector:
  enabled: true
  inject_using_account: activator
  node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
  dal_node_rpc_url: http://dal-dal1:10732
  slot_size: 65536

bootstrap_peers:
  - p2p.riscvnet.jstz.info

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null
snapshot_source: null

images:
  octez: tezos/tezos:octez-v23.2

serviceMonitor:
  enabled: false

protocols:
  - command: PtSeouLo
    vote:
      liquidity_baking_toggle_vote: "pass"

accounts:
  activator:
    # Protocol activation + baking + DAL operations
    # tz1a3bL5hVVibgbaJ7zM3uUJU1iHUgxxpVkU
    key: edpkudGVZdkJRpLXjukh22MrRRJ4puXdn7htgbtGTzRFNkFVbhqH2j
    bootstrap_balance: "1500000000000"
    is_bootstrap_baker_account: true
    type: secret
    dal_node_rpc_url: http://dal-dal1:10732
  injector:
    # jstz-node operations
    # tz1i9R2LwT3SYT9v2NSmwszEXgcViwc3cefY
    key: edpktmz28bvToKv5JzMWM5caFywn9EVeXxJjpqbzUVQ9ttP7SDLsNQ
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "100000000000"
  rollup_operator:
    # Rollup node operations
    # tz1YPNsG4QgLdayDF9tMgKyaPKcS7iN4eXiF
    key: edpkvPsBs3HuFicJCV1V7Es2utwz6qpiLvaadcTPMdLL4RWig4PsXJ
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "100000000000"
  bootstrap1:
    # General purpose/baking
    # tz1VMefR9MZE65reQ7LcnHDJhGkPTCMoCFDj
    key: edpkuBEirLHmeviFVNm2fTUMmdm674NncoC6VMK8dnuwkf6NJBk3ta
    type: secret
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  bootstrap2:
    # General purpose/baking
    # tz1TLYAfMhK2vYNxyRPGBSDSgftdgcfKhZrF
    key: edpktiuF7X5gU6YBewZLA6nM8moFYYNf7TTxTrHZsma9T1U3bRRker
    type: secret
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  bootstrap3:
    # General purpose/baking
    # tz1dgh1aw1qqNjkViP1jGLCe2Pyx57Wx2VCD
    key: edpkuNWkEuvub9fbTVmgJKmcHf6d6XYm6qGUd64xyS6AmhBryWD8xD
    type: secret
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  bootstrap4:
    # General purpose/baking
    # tz1XicAULnibeqjXBsBYKARBWxGiohKYuPr9
    key: edpkuWwrzsT6Voi4bAg2wtFAJKLHwFQ4vQJvwSNuRnBU6hF6MEsgVq
    type: secret
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  bootstrap5:
    # General purpose/baking
    # tz1eEQR5Gf9jnFxtWYn5LUGLCmUHW7rRFjBp
    key: edpkuJj5YqaZ2vrsJ6AHSFaAxBiXCiGCnWoGsWKAGrjvzpAx57dziW
    type: secret
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  faucet:
    # Faucet operations
    # tz1P2DqS58eSkefYpNwmF2Vu2c6fJUx1a9A7
    key: edpkvZVdKNCMXE4AY6B7RQgqGfrr31u6UgFrtqCfH1Ck6vUihBbPRM
    type: public
    bootstrap_balance: "200000000000000"
    is_bootstrap_baker_account: false